GPU: 
  gpu_idx: 0

PROBLEM:
  run_type: "regression" 
  # run_type: "classification" 
  interp_method: "linear"
  # interp_method: "nonlinear"

DATA:
  data_name : "1D_1D_sine"  
  # data_name : '1D_1D_exp' 
  # data_name : "1D_2D_sine_exp"
  # data_name : '2D_1D_sine'
  # data_name : '2D_1D_exp'
  # data_name : '8D_1D_physics' # borehole equation
  # data_name : '10D_5D_physics' # five physics equations

  data_size: 1_000
  split_ratio: [0.7,0.15,0.15]
