MODEL_PARAM: 
  nmode : 40
  nelem : 10
  input_col : [0,1,2,3,4,5,6,7,8,9]
  output_col : [10,11,12,13,14]
  bool_normalize: True # whether we normalize the input data or not
  bool_random_split : True # whether we randomly split the data or not
  data_size: 1000_000
  split_ratio: [0.7,0.15,0.15]

  ## MLP
  nlayers : 3
  nneurons : 100
  # activation : "relu"
  activation : "sigmoid"

TRAIN_PARAM:
  num_epochs : 5
  batch_size : 128
  learning_rate : 1e-3
  bool_train_acc : False
  validation_period : 100 # if this is greater than num_epochs, validation will not be

PLOT:
  bool_plot: False
  plot_in_axis: [3,4] # plot input axis
  plot_out_axis: [0] # plot output axis