MODEL_PARAM: 
  nmode : 1
  nelem : 10
  input_col : [0]
  output_col : [1]
  bool_normalize: False
  data_size: 10_000
  split_ratio: [0.7,0.15,0.15]

TRAIN_PARAM:
  num_epochs : 50
  batch_size : 50
  learning_rate : 1e-3

PLOT:
  bool_plot: False
  plot_in_axis: [0] # plot input axis
  plot_out_axis: [0] # plot output axis