MODEL_PARAM: 
  nmode : 1
  nelem : 20
  input_col : [0]
  output_col : [1,2]
  bool_normalize: False # whether we normalize the input data or not
  bool_random_split : True # whether we randomly split the data or not
  data_size: 10_000
  split_ratio: [0.7,0.15,0.15]

  ## MLP
  nlayers : 3
  nneurons : 21
  # activation : "relu"
  activation : "sigmoid"

TRAIN_PARAM:
  num_epochs_INN : 30
  num_epochs_MLP : 300
  batch_size : 50
  learning_rate : 1e-3
  bool_train_acc : True
  validation_period : 1

PLOT:
  bool_plot: True
  plot_in_axis: [0] # plot input axis
  plot_out_axis: [0,1] # plot output axis