MODEL_PARAM: 
  nmode : 3
  nelem : 5
  input_col : [0,1]
  output_col : [1]

TRAIN_PARAM:
  num_epochs : 50
  batch_size : 50
  learning_rate : 1e-3

PLOT:
  plot_bool: True
  plot_in_axis: [0,1] # plot input axis
  plot_out_axis: [0] # plot output axis