MODEL_PARAM: 
  nmode : 3
  nelem : 20
  input_col : [0,1]
  output_col : [2]
  bool_normalize: False
  bool_random_split : True
  data_size: 10_000
  split_ratio: [0.7,0.15,0.15]

  ## MLP
  nlayers : 3
  nneurons : 20
  # activation : "relu"
  activation : "sigmoid"

TRAIN_PARAM:
  num_epochs : 50
  batch_size : 50
  learning_rate : 1e-3
  validation_period : 1

PLOT:
  bool_plot: True
  plot_in_axis: [0,1] # plot input axis
  plot_out_axis: [0] # plot output axis