MODEL_PARAM: 
  nmode : 10
  nelem : 20
  input_col : [0,1]
  output_col : [2]
  bool_normalize : True # whether we normalize the input data or not
  bool_image : False # this is not an image data
  nclass : 2
  bool_random_split : True
  split_ratio : [0.7,0.15,0.15]

  ## MLP
  nlayers : 3
  nneurons : 100
  # activation : "relu"
  activation : "sigmoid"

TRAIN_PARAM:
  num_epochs_INN : 100
  num_epochs_MLP : 1000
  batch_size : 128
  learning_rate : 1e-2
  bool_train_acc : False # measure train accuracy
  validation_period : 100

PLOT:
  bool_plot: True
  plot_in_axis: [0,1] # plot input axis
  plot_out_axis: [2] # plot output axis
  